version: '3.8'

services:
  # 🚀 Airflow Webserver
  airflow:
    image: apache/airflow:2.7.3-python3.10  # ✅ Usar a imagem oficial do Airflow
    container_name: airflow_duckdb
    restart: always  # ✅ Garante que reinicie se falhar
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./diario_de_bordo:/app/diario_de_bordo
      - ./sensores:/app/sensores
      - ./Airflow/dags:/opt/AirFlow/dags
      - ./desafios.duckdb:/app/desafios.duckdb
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver"
  
  # 🛠 Zookeeper (necessário para Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 🛠 Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 👀 Kafka UI (para visualizar tópicos)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092